---
locale: es
tags: []
layout: input_kids
editor: custom
type: problem
extra_visible: false
teacher_info: Este tipo de actividades nos piden ejecutar un programa dado sin realizar
  modificaciones ni programar nada nuevo, por eso son ideales para analizar, comparar
  o presentar un concepto. Pueden aprovecharse mucho en el aula propiciando intercambios
  en clase para discutir lo que proponen y los resultados que esperamos luego de la
  ejecución.
manual_evaluation: false
choices: []
name: Calentando Motores
